# Generated by Django 4.2.7 on 2024-01-26 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteParameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orphanage_name', models.CharField(max_length=100, verbose_name="Nom de l'orphelinat")),
                ('address', models.TextField(verbose_name="Adresse de l'orphelinat")),
                ('phone_number', models.CharField(max_length=15, verbose_name='Numéro de téléphone')),
                ('opening_hours', models.CharField(max_length=50, verbose_name="Heures d'ouverture")),
                ('about_us', models.TextField(verbose_name='À propos de nous')),
                ('homepage_image', models.ImageField(upload_to='homepage_images/', verbose_name="Image d'accueil")),
            ],
            options={
                'verbose_name_plural': 'Paramètres du site',
            },
        ),
    ]
