# Generated by Django 4.2.7 on 2024-01-26 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0002_visitor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteparameters',
            name='about_us',
            field=models.TextField(blank=True, verbose_name='À propos de nous'),
        ),
        migrations.AlterField(
            model_name='siteparameters',
            name='address',
            field=models.TextField(blank=True, verbose_name="Adresse de l'orphelinat"),
        ),
        migrations.AlterField(
            model_name='siteparameters',
            name='homepage_image',
            field=models.ImageField(blank=True, upload_to='homepage_images/', verbose_name="Image d'accueil"),
        ),
        migrations.AlterField(
            model_name='siteparameters',
            name='opening_hours',
            field=models.CharField(blank=True, max_length=50, verbose_name="Heures d'ouverture"),
        ),
        migrations.AlterField(
            model_name='siteparameters',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, verbose_name='Numéro de téléphone'),
        ),
    ]
