# Generated by Django 5.0.1 on 2024-01-29 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Site', '0003_alter_siteparameters_about_us_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siteparameters',
            name='orphanage_name',
            field=models.CharField(blank=True, max_length=100, verbose_name="Nom de l'orphelinat"),
        ),
    ]
