# Generated by Django 4.2.7 on 2024-01-04 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Utilisateurs', '0003_remove_customuser_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='numero',
            new_name='username',
        ),
    ]
