# Generated by Django 4.2.7 on 2024-01-08 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utilisateurs', '0012_remove_customuser_confirmation_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='last_logout',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
