# Generated by Django 4.2.7 on 2024-01-08 11:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Utilisateurs', '0014_alter_customuser_last_logout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='last_logout',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
