# Generated by Django 4.2.7 on 2024-01-08 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utilisateurs', '0015_alter_customuser_last_logout'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='unread_messages',
            field=models.IntegerField(default=0),
        ),
    ]
