# Generated by Django 4.2.7 on 2024-01-09 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utilisateurs', '0020_blogpost_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='show_full_content',
            field=models.BooleanField(default=False),
        ),
    ]
