# Generated by Django 4.2.7 on 2024-01-09 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Utilisateurs', '0021_blogpost_show_full_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='show_full_content',
        ),
    ]
