# Generated by Django 5.0.1 on 2024-01-29 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Utilisateurs', '0025_remove_blogpost_images_blogpost_image_delete_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='image',
            new_name='images',
        ),
    ]
