# Generated by Django 5.0.1 on 2024-01-29 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utilisateurs', '0027_blogimage_remove_blogpost_images_blogpost_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogimage',
            name='blog_post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='blog_images', to='Utilisateurs.blogpost'),
        ),
    ]
