# Generated by Django 5.0.1 on 2024-01-29 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utilisateurs', '0028_blogimage_blog_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='images',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_images/'),
        ),
        migrations.DeleteModel(
            name='BlogImage',
        ),
    ]
